### PR TITLE
feat(main): add custom scope prompt

### PR DESCRIPTION
**Pull request by Todomir**
I think we should be able to add an custom scope when it is enabled. Right now I'm just injecting an extra option with the value of "custom", but maybe this could be enabled via config.

### CODE REVIEW

**Comment by Everduin94** [comment]
Do you have a real-world example of this in mind?

Since scope is optional. I can't really think of a scenario where someone would add a custom scope 1 time that wouldn't be useful to be used again, or by another developer. i.e. if none of the existing scopes are applicable, and it doesn't make sense to add the new one to the config, you would usually just omit scope altogether.

If there are good examples or others might find it useful I don't have a problem adding it.

**Comment by Todomir** [comment]
Usually, I use custom scopes when targeting specific files or folders that are nested in other folders so that it is clear on the commit what was changed. Maybe it is not compliant with the Conventional Commits spec, but it is an use case. Also, if you have a lot of scopes it can be a hassle to find them in the list, so typing could be an alternative.

**Comment by Everduin94** [comment]
@Todomir - Makes sense. 

Ideally for long scope lists we need the upstream to add this: "List Search" https://github.com/natemoo-re/clack/issues/35

I've added custom scope as default false. A few things on my PR that led me to create a new one:
- Handled by config
- Passed through ZOD object, otherwise intial_value: "custom" would have failed
- Added to documentation
- Removed validate since scope is optional and the commit builder handles empty gracefully.

See: #21

**Comment by Todomir** [comment]
Yeah, list search feature benefit the package a lot. I usually work with an Gitmoji + Convetional hybrid and Gitmoji has way more prefixes than Conventional. Searching would be superb

**Pull request closed without merging**
